# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

services:
  karakuri-agent-app-dev:
    build: Dockerfile-dev
    container_name: "karakuri-agent-app-dev"
    tty: true
    command: sleep infinity
    ports:
     - "50505:50505"
    volumes:
      - ./:/home/ubuntu/workspace/karakuri_agent
