# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

name: karakuri_agent
description: "Karakuri agent."
publish_to: 'none'

version: 0.2.1+12

environment:
  sdk: ^3.5.3
  flutter: "3.24.5"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  slang: ^4.4.0
  slang_flutter: ^4.4.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  path: ^1.9.0
  sqflite: ^2.4.1
  sqflite_common_ffi_web: ^0.4.5+4
  http: ^1.2.2
  audioplayers: ^6.1.0
  idb_shim: ^2.6.1+7
  archive: ^4.0.2
  flutter_svg: ^2.0.16
  image: ^4.5.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  speech_to_text: ^7.0.0
  async: ^2.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_style: ^2.3.7
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  riverpod_generator: ^2.6.3
  slang_build_runner: ^4.4.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  rps: ^0.9.1

dependency_overrides:
  # TODO rps override
  meta: ^1.16.0 
  http: ^1.2.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

scripts:
  clean: flutter clean
  get: flutter pub get
  gen: dart run build_runner build --delete-conflicting-outputs
  clean-gen: dart run rps clean && dart run rps get && dart run rps gen
  build:  
    apk: flutter build apk ${0} --obfuscate --split-debug-info=obfuscate/android
    appbundle: flutter build appbundle ${0} --obfuscate --split-debug-info=obfuscate/android
    web: flutter build web
  flutter-run:
    default: flutter run ${0} 
    web: flutter run -d web-server --web-hostname=0.0.0.0 --web-port=50505 ${0} 
  build-debug:
    apk: rps build apk --debug
    appbundle: rps build appbundle --debug
    web: rps build web
  build-release:
    apk:
      $before: dart run rps clean-gen
      $script: rps build apk --release
    appbundle:
      $before: dart run rps clean-gen
      $script: rps build appbundle --release
    web: 
      $before: dart run rps clean-gen
      $script: rps build web
  run-release:
    default:
      $before: dart run rps clean-gen
      $script: dart run rps flutter-run default --release
    web:
      $before: dart run rps clean-gen
      $script: dart run rps flutter-run web --release
  run-debug:
    default: dart run rps flutter-run default --debug
    web: dart run rps flutter-run web --debug
