# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

name: build

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build-android-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-app-dev:latest
      options: --user root
    env:
      KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}
      KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/ubuntu/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - uses: actions/cache@v3
        with:
          path: |
            /home/ubuntu/android-sdk/build-tools
            /home/ubuntu/android-sdk/platforms
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-android-sdk-
      - run: echo '${{ secrets.ENCODED_RELEASE_KEYSTORE }}' | base64 --decode > android/playstore.keystore
      - name: Add Flutter to PATH
        run: echo "/home/ubuntu/flutter/bin" >> $GITHUB_PATH
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: dart run rps build-release apk
      - uses: actions/upload-artifact@v3
        with:
          path: build/app/outputs
          retention-days: 1
  build-web-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-app-dev:latest
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /home/ubuntu/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: ${{ runner.os }}-flutter-
      - uses: actions/cache@v3
        with:
          path: |
            /home/ubuntu/android-sdk/build-tools
            /home/ubuntu/android-sdk/platforms
          key: ${{ runner.os }}-android-sdk-${{ hashFiles('**/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-android-sdk-
      - name: Add Flutter to PATH
        run: echo "/home/ubuntu/flutter/bin" >> $GITHUB_PATH
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: dart run rps build-release web
      - uses: actions/upload-artifact@v3
        with:
          path: build/web
          retention-days: 1
