# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

name: docker-build

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write


jobs:
  build-docker:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: release-docker
        run: |
          docker build --tag ghcr.io/karakuriagent/karkuri-agent-flutter-client-dev:latest \
            --no-cache \
            --file Dockerfile-dev .
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Packages
        run: docker push ghcr.io/karakuriagent/karkuri-agent-flutter-client-dev:latest
