# Copyright (c) 0235 Inc.
# This file is licensed under the karakuri_agent Personal Use & No Warranty License.
# Please see the LICENSE file in the project root.

name: release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release-android-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-app-dev:latest
      options: --user root
    env:
      KEYSTORE_ALIAS: ${{ secrets.RELEASE_KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_ALIAS_PASSWORD }}
      KEYSTORE_STORE_PASSWORD: ${{ secrets.RELEASE_KEYSTORE_STORE_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo '${{ secrets.ENCODED_RELEASE_KEYSTORE }}' | base64 --decode > android/playstore.keystore
      - name: Add Flutter to PATH
        run: echo "/home/ubuntu/flutter/bin" >> $GITHUB_PATH
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: dart run rps build-release apk
      - run: zip -r build/mapping.zip build/app/outputs/mapping/release
      - run: zip -r build/dartDebugSymbols.zip obfuscate/android
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/app/outputs/apk/release/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/apk
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/mapping.zip
          asset_name: mapping.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/dartDebugSymbols.zip
          asset_name: dartDebugSymbols.zip
          asset_content_type: application/zip
  release-web-app:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/0235-jp/karkuri-agent-app-dev:latest
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Add Flutter to PATH
        run: echo "/home/ubuntu/flutter/bin" >> $GITHUB_PATH
      - run: git config --global --add safe.directory /home/ubuntu/flutter
      - run: dart run rps build-release web
      - run: zip -r build/web.zip build/web
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/web.zip
          asset_name: web.zip
          asset_content_type: application/zip
